### ISSUE TITLE
Allow disks to be created and attached for virtualbox

### ISSUE THREAD

**Issue by kramvan1** [test-kitchen/kitchen-vagrant#108]
When using virtual box, would be nice to allow additional storage to be easily created and/or attached to a vm.  Something like this:

driver:
  name: vagrant
  attached_disks:
    - ["sdb.vdi", "500", "1", "0", "hdd"]

Would allow for a persistent disk image to be used easily in all test environments.

**Comment by alainchiasson** [comment]
I have done the following (works for 0.15.0). 

The kitchen.yml file has the following: 

```
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb
  vagrantfiles:
    - /Files/Vagrant.Disk.rb
```

The Vagrantfile.erb file is the "next" version - what is currently in master (I guess what will be in 0.16 - once the 0.16 template is released that line will no longer be required) 

/Files/Vagrant.Disk.rb is a Vagrant file to merge in : 

```
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |vb|
     vb.customize ["createhd", "--filename", "disk.vdi", "--size", "1024"]
     vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--medium", "alch-2014.vdi", "--port", "0", "--device", "1", "--type", "hdd"]
  end
end
```

My file will create and attach a disk - but it will get destroyed when you "kitchen destroy". It may be you will need to "clonehd" of an existing disk - or there may be a way to stop Vagrant/kitchen from destroying resources.

I hope this helps.

**Comment by kramvan1** [comment]
@alainchiasson thx for the post, this look good. Probably should push that into the README at some point.

**Comment by spuder** [comment]
Where is the /Files/Vagrant.Disk.rb placed? Is this supposed to be inside the VM, or inside the files directory of my cookbook?

**Comment by tsupertramp** [comment]
It is placed inside your cookbook.
