### ISSUE TITLE
Please Create New Release for better Vagrant 1.6+ Compatibility

### ISSUE THREAD

**Issue by tknerr** [test-kitchen/kitchen-vagrant#125]
Just stumbled across [hard to track down ssh connection timeouts](https://github.com/test-kitchen/test-kitchen/issues/464) while trying to get kitchenci run on a Hyper-V build worker.

I was under the definitive impression that I was using a 32-bit box. My `.kitchen.yml` here:
```
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: chef/ubuntu-12.04-i386
```

However, as of `0.15.0` the `default_box_url` is ALWAYS generated:
https://github.com/test-kitchen/kitchen-vagrant/blob/v0.15.0/lib/kitchen/driver/vagrant.rb#L108-114

In my case it would use the `platform.instance.name` as a basis and thus I was getting the 64 bit box rahter than the `chef/ubuntu-12.04-i386` box I specified in the driver config.

In master there is a fix to make the above example work as expected with Vagrant 1.6+ where only the box name is needed:
https://github.com/test-kitchen/kitchen-vagrant/blob/master/lib/kitchen/driver/vagrant.rb#L115-L116

It would be awesome if this would go into a kitchen-vagrant release, since vagrant 1.6 is out for quite a while already. Any plans for the next (0.16.0?) release already?

**Comment by tknerr** [comment]
@fnichol @sethvargo mind pushing a new kitchen-vagrant release as well while you're at it?

**Comment by tknerr** [comment]
just another issue that the 0.15.0 behaviour (i.e. the need to specify both box + box_url for atlas hosted boxes) causes is that the box version is always reported as 0:
```
W:\>vagrant box list
chef/ubuntu-12.04-i386 (virtualbox, 0)
chef/ubuntu-14.04      (virtualbox, 0)
```

(these boxes were downloaded / added as part of a kitchenci w/ kitchen-vagrant 0.15.0 run)

I we could use the "<account>/<boxname>" syntax that came with vagrant 1.6 this would work properly with box versioning too...

**Comment by fnichol** [comment]
Okay, [0.1.6.0 released](https://rubygems.org/gems/kitchen-vagrant/versions/0.16.0)!
