### ISSUE TITLE
config[:ssh] causing Vagrantfile.erb to fail.

### ISSUE THREAD

**Issue by tejaycar** [test-kitchen/kitchen-vagrant#131]
Thanks to #108 I was trying to use the new Vagrantfile.erb with `vagrantfiles`.  I got a `no method [] on nil` type error throwing from https://github.com/test-kitchen/kitchen-vagrant/blob/master/templates/Vagrantfile.erb#L39 due to an empty `config[:ssh]`.   I'm not familiar enough with the internals to know why `config[:ssh]` might have been null, but I'm assuming there is a bug of some sort here.

**Comment by alainchiasson** [comment]
I tried what I had done before (for #108) with the latest Vagrantfile.erb and it also failed with an error. It did work with the file I had downloaded.  

For reference - I have created a quick repo : https://github.com/alainchiasson/vbox_disk_demo

**Comment by fnichol** [comment]
@tejaycar and @alainchiasson  Hi there! I'm hoping that bf38f9492798b995befc70723166ede8f3b3c96e resolved this issue and has shipped out in the 0.16.0 release.

If I'm totally off the mark, please re-open or file a new issue. Hopefully we're smooth sailing now :smile:
