### ISSUE TITLE
Query on .kitchen.yml location and cookbook path

### ISSUE THREAD

**Issue by wingZero21** [test-kitchen/kitchen-vagrant#133]
Hi,

I am trying to use kitchen-vagrant plugin however I am not sure wheres its picking up the cookbook path from.

So when running the kitchen test command everything seems to be fine but how do you set it to match the location of the cookbooks that is being set in vagrant.

For example I am setting the cookbook path from my local folder to a vagrant_data folder.

Does the .kitchen.yml file have to be in the cookbook root directory to run?

**Comment by tknerr** [comment]
@wingZero21 I believe the typical use case is that you are using berkshelf and have a `Berksfile` present in the same directory where you have your `.kitchen.yml`. 

The `Berksfile` defines the cookbook dependencies and test-kitchen will resolve them via berkshelf during the kitchen run. It will *automatically configure*  the cookbooks directory for you so you shouldn't have to care about that.

If you really want to change that location, no idea if that is supposed to work or not...

**Comment by cheeseplus** [comment]
From http://kitchen.ci/docs/getting-started/adding-dependency

```
1.  Do you have a Berksfile in your project directory? If so, Test Kitchen will use Berkshelf to resolve dependencies.
2.  Do you have a Cheffile in your project directory? If so, Test Kitchen will use Librarian-Chef to resolve dependencies.
3.  Do you have a cookbooks/ directory in your project directory? If so, Test Kitchen will use that.
4.  Do you have a metadata.rb file in your project directory? If so, then this project is a cookbook and Test Kitchen will use that.
5.  Otherwise we're out of options, so Test Kitchen will create a fake cookbook and use that so that Chef has just enough to perform an empty Chef run.
```
