### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by fromonesrc** [test-kitchen/kitchen-vagrant#135]
Hi maintainers. Can we please get a new release of this gem? Seeing some incompatibility with newer versions of Vagrant on the latest released version that have been fixed on master.

**Comment by sethvargo** [comment]
We will release a new version when it's ready :smile:

**Comment by fromonesrc** [comment]
How can I help?

**Comment by tknerr** [comment]
see also #125 

Would love to see a new release too :-)
