### ISSUE TITLE
kitchen not detecting vagrant plugin `kitchen-vagrant`

### ISSUE THREAD

**Issue by xacaxulu** [test-kitchen/kitchen-vagrant#143]
Ubuntu 14.10 fresh install

    chef@ubuntu:~/db2$ uname -a
    Linux ubuntu 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

    chef@ubuntu:~/db2$ vagrant -v
    Vagrant 1.4.3
    chef@ubuntu:~/db2$ vagrant plugin list
    kitchen-vagrant (0.15.0)
    chef@ubuntu:~/db2$ chef -v
    Chef Development Kit Version: 0.4.0
    chef@ubuntu:~/db2$ 

    chef@ubuntu:~/db2$ kitchen converge --parallel
    -----> Starting Kitchen (v1.3.1)
    -----> Creating <default-centos-511>...
    -----> Creating <default-fedora-20>...
       The plugin "kitchen-vagrant" could not be found. Please make sure that it is
       properly installed via `vagrant plugin`. Note that plugins made for
       Vagrant 1.0.x are not compatible with 1.1+ and this error will likely
       continue to show when you use `plugin install` with a 1.0.x plugin.

Running `chef exec kitchen test` & `kitchen test` return the same error message even though `gem list`, `chef gem list`, `vagrant plugin list` all show the `kitchen-vagrant` gem/plugin installed.

Why does `kitchen` not detect the vagrant plugin `kitchen-vagrant` even though it's listed as installed?

**Comment by DaveCasey** [comment]
I don't know if this is related, but after installing
  test-kitchen 1.4.0.rc.1
  kitchen-vagrant 0.17.0.rc.1
kitchen init started returning: "Message: Could not load the 'vagrant' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler."

If I roll back the kitchen-vagrant gem
kitchen-vagrant 0.15.0
kitchen list then behaves as expected.

chef -v
  Chef Development Kit Version: 0.4.0

vagrant -v
  Vagrant 1.7.2

Darwin Kernel Version 12.6.0

Let me know if there is any additional information I can provide that would be helpful.

**Comment by DaveCasey** [comment]
Additional note: after I upgraded chefdk from 0.4.0 to 0.5.0.rc5, kitchen-vagrant 0.17.0.rc.1 now works great.  I guess if I'm going to live in the future, I shouldn't do it half-way.

Thanks Galen!

**Comment by cheeseplus** [comment]
This issue should be resolved in current version of the gems and Vagrant. Feel free to open new issues if issues still persist.
