### ISSUE TITLE
Customize vm.name in Vagrantfile.erb

### ISSUE THREAD

**Issue by DennyZhang** [test-kitchen/kitchen-vagrant#144]
If we want to customize VM name in vm list of virtualbox, we can customize vm.name in Vagrantfile.

Looks like Vagrantfile.erb currently doesn't support us to do that.

Thanks.

**Comment by DennyZhang** [comment]
Something like this in Vagrantfile

  config.vm.provider :virtualbox do |vb|
    vb.name = "mytest.dennyzhang.com"
    vb.customize ["modifyvm", :id, "--memory", MEMORY_MB, "--cpus", "2"]
  end

**Comment by DennyZhang** [comment]
It's supported indeed like below, though not that apparent.

We can mark it as INVALID now.

Vagrangfile
driver:
  name: vagrant
driver_config:
  use_sudo: false
  customize:
      name: kitchen-vagrant-ubuntu-1404

**Comment by fnichol** [comment]
@DennyZhang, glad you were able to sort this out without any code changes, yay!

I'm assuming you had a reason for wanting to set the `vm.name`--care to add some insight for me so I can better understand?

As it looks like you're good to go here, I'll close this out and feel free to reopen if I've misunderstood. Thanks!

**Comment by DennyZhang** [comment]
@fnichol I have multiple VMs in virtualbox, so I'd like to differentiate them by name in the list.

**Comment by fnichol** [comment]
@DennyZhang as of #101 (released in 0.16.0+), the names in VirtualBox (and VMware) should be named something like:

  "`kitchen-#{project_directory_name}-#{instance_name}`"

Would that help?
