### ISSUE TITLE
new release for rubygems user?

### ISSUE THREAD

**Issue by rmoriz** [test-kitchen/kitchen-vagrant#145]
Hi,

latest version of kitchen-vagrant on rubygems.org is 0.15.0 from April 28, 2014 and misses a lot of the changes/fixes that got merged on master. Could you please release a new version?

Thanks!

**Comment by joerg** [comment]
+1
I was just about to write the same "complaint"... ;)

**Comment by JonathanPorta** [comment]
+1 I would find this useful too.

**Comment by fnichol** [comment]
Good morning (from where I am)! Version 0.16.0 has (finally) [shipped](https://rubygems.org/gems/kitchen-vagrant/versions/0.16.0)!
