### ISSUE TITLE
find way to auto detect winrm port (or alternatively list host only network)

### ISSUE THREAD

**Issue by jmahowald** [test-kitchen/kitchen-vagrant#153]
I suspect that the most correct answer in a vacuum would be to patch vagrant to have an equivalent to ssh-config which outputs the mapped port of 22.  I imagine some of the code used to enable 
   vagrant rdp 
could be leveraged (though for WinRM of course).  

I assume that the change in this case would be in vagrant.rb#update_state

I don't like the idea of searching stdout from a vagrant up command, but I've done that in the past to handle vagrant reloads.

**Comment by fnichol** [comment]
@jmahowald Thanks for getting this into an issue. The solution I'm looking at for this is a custom Vagrant plugin that would be similar to `vagrant ssh-config`, perhaps `vagrant winrm-config` which would return similar data than that of `ssh-config` but for WinRM and RDP.

It seems like this happens for some Vagrant providers and when private networks are used, which is all valid--it just didn't come up for me working on the feature.

I'll want this ready in a 0.17.0 release, but will most likely release a 0.17.0.beta.1 in the meantime to let others test the remainder of the 2 code bases

I'll update this issue with updates.

Thanks!

**Comment by fnichol** [comment]
The fix that should address this issue is in the 0.17.0.beta.3 release.
