### ISSUE TITLE
Add RDP port forwarding when transport is WinRM

### ISSUE THREAD

**Issue by jmccann** [test-kitchen/kitchen-vagrant#160]
When I used Salim's fork of test-kitchen and kitchen-vagrant it would create the port forwarding for RDP.  Right now when I do kitchen login for a windows guest it doesn't work.  I need to go into virtualbox and add port forwarding for RDP first then kitchen login to a windows guest works.

Seems perhaps this commit added the wanted functionailty: https://github.com/afiune/kitchen-vagrant/commit/cdfe201d34d3c75c61510551fa9be46633523125

Example of my issue:

```
-----> Starting Kitchen (v1.4.0.rc.1)
-----> Creating <default-win-2012r2>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'opentable/win-2012r2-standard-amd64-nocm'...
==> default: Matching MAC address for NAT networking...
       ==> default: Checking if box 'opentable/win-2012r2-standard-amd64-nocm' is up to date...
       ==> default: Setting the name of the VM: kitchen-network_interfaces_v2-default-win-2012r2_default_1428506743441_38540
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 5985 => 55985 (adapter 1)
           default: 22 => 2222 (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
```

Notice how SSH and winrm ports are configured but not RDP.

**Comment by cheeseplus** [comment]
This is working with latest TK and kitchen-vagrant so I'm closing the issue.
