### ISSUE TITLE
Could not load the 'vagrant' driver from the load path.

### ISSUE THREAD

**Issue by dgorack** [test-kitchen/kitchen-vagrant#164]
In my `~/chef-repo/Gemfile` I've added `gem 'test-kitchen'` and ran `bundle update`.

In my `~/chef-repo/cookbooks/git` I ran `kitchen init`. When I do `kitchen list` I get:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'vagrant' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

I have the default `.kitchen.yml` file.

```
Chef Development Kit Version: 0.4.0
Chef: 12.0.3
Vagrant 1.7.2
```

Gem list includes:
```
test-kitchen (1.4.0, 1.3.1)
kitchen-vagrant (0.17.0, 0.15.0)
```

**Comment by ehorne** [comment]
Rolling back to 0.16.0 addressed the issue; similar parameters as above..

**Comment by dgorack** [comment]
Doing a `gem install kitchen-vagrant -v '0.16.0'`
Results in:
```
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/dgorack/.chefdk/gem/ruby/2.1.0/gems/kitchen-vagrant-0.16.0/.gitignore
```

I shouldn't have to use sudo for this should I?

**Comment by bbc88ks** [comment]
Rolling back to 0.16.0 helped

**Comment by dgoradia-atlas** [comment]
That's not very helpful. I'm telling you that I tried and failed and posting the error message. Maybe I'm not getting what's meant by rolling back so please tell me exactly what I have to do to roll back to 0.16.0.

**Comment by ehorne** [comment]
Oh sorry.. I'm not sure what's broken in either my environment or the released code, but 0.17.0 when it was pulled onto my system broken the test kitchen. So I went into my gems folder in my home directory and renamed the 0.17 release to 0.17.0bad -- effectively hiding it from ruby. I'm quite sure there is a better way to remove that gem properly, though I'm not much of a ruby guy and just did what I needed to do to make the pain stop :) Hope that helps.

**Comment by 501st-alpha1** [comment]
I also had this problem, and can confirm that rolling back to version `0.16` of `kitchen-vagrant` fixed the issue for me.

**Comment by chaim1221** [comment]
yeah same here

**Comment by s2t2** [comment]
I got this error after using bundler to install the `kitchen-ec2` driver. Even though there is no Gemfile in the directory anymore, `kitchen` commands are not working. I'm getting error messages about the PATH and its all very confusing.

**Comment by cheeseplus** [comment]
This condition should no longer exist and it appears not all of the issues in thread are related - if using ChefDK then you will have test-kitchen already embedded in that Ruby context. If anyone has an issue please open a new one with current logs.
