### ISSUE TITLE
kitchen-vagrant doesn't work with unknown Bento boxes

### ISSUE THREAD

**Issue by juliandunn** [test-kitchen/kitchen-vagrant#165]
`kitchen-vagrant` only seems to work with known Bento boxes as specified in [this array](https://github.com/test-kitchen/kitchen-vagrant/blob/master/lib/kitchen/driver/vagrant.rb#L194-L200).

If you try to use a Bento box that it doesn't know about (example: `centos-7.1`) then the Vagrantfile it creates is invalid and doesn't point to a box URL that can be downloaded by Vagrant, because it doesn't supply a box URL and `centos-7.1` is not a known box on Atlas.

Incorrect:

```ruby
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "centos-7.1"
  c.vm.hostname = "default-centos-71"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
```

Expected:

```ruby
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "opscode-centos-7.1"
  c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box"
  c.vm.hostname = "default-centos-71"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
```

I narrowed it down to [this commit](https://github.com/test-kitchen/kitchen-vagrant/commit/a2ef401fb5a644c96165ce836ff3e6379637a37f).

**Comment by fnichol** [comment]
I think this is mostly mitigated with #166 but the issue around determining "platform name to known Bento boxes" remains for now.

If I've totally missed the point here, please do reopen. Thanks!
