### ISSUE TITLE
Private key permissions too open on Windows

### ISSUE THREAD

**Issue by tpetchel** [test-kitchen/kitchen-vagrant#177]
There's been anecdotal talk about permission issues with the private key while working with Linux instances from Windows. Here's evidence from one user:

https://learn.chef.io/local-development/rhel/get-started-with-test-kitchen/#comment-2060762441

I don't know if this is specific to Windows 7, or if it applies to 8.1 and 10 as well.

Hoping someone can investigate. Thanks!

**Comment by cheeseplus** [comment]
Looks like this one has been resolved but feel free to open again if we see similar.
