### ISSUE TITLE
Add vagrant-cachier support to default Vagrantfile.erb

### ISSUE THREAD

**Issue by tfitch** [test-kitchen/kitchen-vagrant#186]
I know that there is now the ability to use a custom Vagrantfile template or inject arbitrary code in to the Vagrantfile, but I'm still interested in adding this addition because it would be reverse compatible (because of the if + has_plugin? combo) for those that don't use the vagrant-cachier plugin. https://github.com/fgrehm/vagrant-cachier

So as a user I want support for the vagrant-cachier plugin if I have it installed on my machine by adding these lines to the default `Vagrantfile.erb` template.

```
  if Vagrant.has_plugin?("vagrant-cachier")
    c.cache.scope = :box
    c.cache.auto_detect = true
  end
```

But it's not that simple to implement well because scope and auto_detect have a couple of value options, so we'd want them to be configurable and not force people to use just that combination of values.  That said, we need to draw a line somewhere and this is a great basic implementation.  If the user wants to dig in to advanced vagrant-cachier settings like `synched_folder_opts` then they need to go in to Test Kitchen power user mode with a custom `Vagrantfile.erb` or inject the custom settings.

**Comment by tknerr** [comment]
@tfitch I have this in my global `~/.vagrant.d/Vagrantfile`. This kicks in for every test kitchen:
https://github.com/tknerr/bills-kitchen/blob/master/files/home/.vagrant.d/Vagrantfile#L9-L27

**Comment by cheeseplus** [comment]
I'm all for supporting a feature/config option that makes this easy but I also don't want to make it default. The one scenario I am envisioning is if someone has the plugin installed but doesn't intend or want to use it. I think a configuration option makes more sense - that or abstracting this to a plugin.

**Comment by cheeseplus** [comment]
Also - https://github.com/test-kitchen/kitchen-vagrant/pull/200 where I've made the same request to make this toggleable to prevent it from even getting into the Vagrantfile.
