### ISSUE TITLE
How to assign an external IP in kitchen.yml, then read that value (using Ohai) and assign to an attribute?

### ISSUE THREAD

**Issue by Joseph-R** [test-kitchen/kitchen-vagrant#189]
Hey guys,

We're looking to migrate our development environment within Kitchen to make it easier to develop, test, and modify this legacy code.

I'm encountering a lot of hard-coded IP and hostname/FQDNs in our legacy code.  I would like pull that stuff out, assign these to each node in kitchen, then have Ohai read these attributes during the client run and fill them in as attributes.

In my **kitchen.yml**:
```
suites:
  - name: analytics
    driver:
      vm_hostname: analytics
      network:
      - ["private_network", {ip: "33.33.33.110"}]
    run_list:
      - recipe[hostname::default]
```

But Ohai sets `node['ipaddress']` to the `10.0.x.x` IP assigned eth0.   It looks like Ohai always sets ipaddress to the first ethernet port, and does not appear to index other ports.

**ifconfig**:
```
[root@analytics-centos-65 vagrant]# ifconfig
eth0      Link encap:Ethernet  HWaddr 08:00:27:D4:16:F5
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fed4:16f5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:92083 errors:0 dropped:0 overruns:0 frame:0
          TX packets:32736 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:76250742 (72.7 MiB)  TX bytes:2393919 (2.2 MiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:E6:84:B8
          inet addr:33.33.33.110  Bcast:33.33.33.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fee6:84b8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1691 errors:0 dropped:0 overruns:0 frame:0
          TX packets:110 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:224097 (218.8 KiB)  TX bytes:12276 (11.9 KiB)
```

So what is the best way to assign an IP in kitchen-vagrant and pull that assigned value out as an attribute on the box itself?

**Comment by cheeseplus** [comment]
Ohai does indeed enumerate all network devices under node['network']['interfaces'] - the ['ipaddress'] that  gets set is simply the default route. I'm closing this as it isn't an issue with test-kitchen as such but how Ohai enumerates network interfaces. Happy to answer any questions though so feel free to open a new issue or re-open this one.
