### ISSUE TITLE
Default bento boxes should be pulled from Atlas

### ISSUE THREAD

**Issue by cheeseplus** [test-kitchen/kitchen-vagrant#193]
Now that https://github.com/chef/bento is reliably pushing boxes to the Atlas [bento](https://atlas.hashicorp.com/bento) organization the default kitchen-vagrant behaviour should be changed to pull from Atlas instead of S3.

Boxes will continue to be pushed to S3 for back compat but as S3 lacks the versioning and updating that Atlas offers it should only be used as a fallback until we can fully deprecated S3 support in the driver.

**Comment by cheeseplus** [comment]
bump pre-Rally <3

**Comment by kisoku** [comment]
:+1:

can we please ship this ?

**Comment by cheeseplus** [comment]
Going to ship this in the next release - pretty much my target feature but I'll also pull in any other small fixes.
