### ISSUE TITLE
Nfs synced_folders requires sudo access on Mac host machine to edit /etc/exports

### ISSUE THREAD

**Issue by danapplegate** [test-kitchen/kitchen-vagrant#199]
Hi,

I've tried to get nfs synced_folders working, as indicated in the README. However, to do this, Vagrant requires sudo-level access on the host machine (mine is MacOSx) in order to edit the /etc/exports file. Because test kitchen runs without a TTY, Vagrant is never able to ask for my host machine's sudo password, and I get a message like: "sudo: no tty present and no askpass program specified".

Has anyone been able to get nfs folders working on MacOSx? Is there something I'm missing to get this working?

**Comment by builtinnya** [comment]
@danapplegate 
Add the following lines to `/etc/sudoers`:
```
Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
Cmnd_Alias VAGRANT_NFSD = /sbin/nfsd restart
Cmnd_Alias VAGRANT_EXPORTS_REMOVE = /usr/bin/sed -E -e /*/ d -ibak /etc/exports
%admin ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE
```
For more information, please refer to [NFS - Synced Folders - Vagrant Documentation](https://docs.vagrantup.com/v2/synced-folders/nfs.html)

**Comment by cheeseplus** [comment]
Closing this as the above answer is perfect.
