### ISSUE TITLE
support for docker with kitchen-vagrant

### ISSUE THREAD

**Issue by anupkpachlag** [test-kitchen/kitchen-vagrant#206]
Currently I am trying to use kitchen-vagrant with docker as the provider. vagrant when run with docker provider does not really need a basebox. Unfortunately kitchen-vagrant makes the basebox required. This becomes a blocking issue.  
Can kitchen-vagrant support docker without requiring a basebox ?

**Comment by cheeseplus** [comment]
Why not just use https://github.com/someara/kitchen-dokken? Vagrant also supports some cloud interfaces directly as well but we don't support them because there are individual drivers that are superior.

**Comment by xmik** [comment]
There is also [kitchen-docker_cli](https://github.com/marcy-terui/kitchen-docker_cli) which I use all the time.

**Comment by cheeseplus** [comment]
There are better drivers that have been provided as solutions - if someone wanted to do a PR to add docker features I'd be happy to merge but given the above it's not felt terribly necessary.
