### ISSUE TITLE
Vagrant 1.8.1 colors mess up vagrant_plugin_installed?

### ISSUE THREAD

**Issue by oifland** [test-kitchen/kitchen-vagrant#207]
Vagrant seems to have recently added ANSI colors to the output and that means extra characters are showing up. When `vagrant_plugin_installed?`is called, it's splitting on newlines and then checking to see if the plugin is at the beginning of the line (see https://github.com/test-kitchen/kitchen-vagrant/blob/ff8cb079c79aed9c5ed90142063db28f0728a0db/lib/kitchen/driver/vagrant.rb#L443 )

The characters "\e[0m" are showing at the beginning of the line, which mess up the /^plugin-name\s+/ regex.

There are options for turning off the colors - see VAGRANT_NO_COLOR and --no-color https://www.vagrantup.com/docs/other/environmental-variables.html

Another option could be to make the regex more forgiving.

**Comment by oifland** [comment]
While it's not causing a problem with the current regex, the `split("\n")` should probably change to `split(/\R/)` for consistent results across platforms

**Comment by dougireton** [comment]
The bug causes this problem. Kitchen-vagrant doesn't think the vagrant-winrm Vagrant plugin is installed because the extra leading ANSI color sequences mess up the regex.

```
 kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: WinRM Transport requires the vagrant-winrm Vagrant plugin to properly communicate with this Vagrant VM. Please install this plugin with: `vagrant plugin install vagrant-winrm' and try again.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by dougireton** [comment]
I'm working on a PR for this.

**Comment by dougireton** [comment]
This appears to be a Windows-only issue.

**Comment by Kazark** [comment]
:+1:

**Comment by akemner** [comment]
this is a really annoying bug, thanks for the link above to the ENV options @oifland . i'm going to post it directly here in case other people run into this. 

work around is `[Environment]::SetEnvironmentVariable("VAGRANT_NO_COLOR","false","Machine")`

**Comment by dougireton** [comment]
@akemner Don't you wan't `VAGRANT_NO_COLOR` to be `true`?

**Comment by Kazark** [comment]
@akemner @dougireton Thanks guys. I did the ugly thing of actually editing the Ruby file. Very glad to see there is a better way.

**Comment by phillipbroberts** [comment]
@Kazark @akemner where are you guys placing this?

**Comment by Kazark** [comment]
@phillipbroberts I forget, sorry. It's been a while since I did it and if I recall, it has been fixed now.

**Comment by ghbrown60640** [comment]
bumping on this. I'm having this issue as well.

**Comment by cheeseplus** [comment]
This should be covered by #309 but if not please open a new issue with current version of Vagrant, kitchen-vagrant, etc.
