### ISSUE TITLE
Using kitchen_root as part of the instance name produces clashes or too long names

### ISSUE THREAD

**Issue by arielsalvo** [test-kitchen/kitchen-vagrant#210]
Hi,

I have issue with using {kitchen_root_directory} as part of the instance name due to directories with the same name or producing instance names that are too long.

How about using a CRC32 of the full path?
It would make the instance name unique and shorter, getting the actual path would still be easy by running vagrant global-status and it should be quite easy to implement too.

Any thoughts?

**Comment by rlaveycal** [comment]
I'd like to +1 this as I've been battling a problem with the Hyper-V provider and path name exceeding the 260 character limit in Windows caused by the concatenation of cookbook, suite and platform. I'd also like to suggest that `instance.name` is CRC'ed to shorten the path further.

**Comment by cheeseplus** [comment]
I closed the existing PR but will open a new one myself

**Comment by jkerry** [comment]
+1 here. We started running into numerous windows agent build failures after pushing an upgrade to chefdk 2.1.11

**Comment by cloneluke** [comment]
+1 encountered major issues launching vagrant from windows test-kitchen after chefdk 2.1

Also think it might have to do with this commit not allowing spaces in path name on line 429:

https://github.com/test-kitchen/kitchen-vagrant/commit/a946fb68777b52413c66d9790eb56d440c03c82d#diff-746c6817cd7ffe8b6bd9acc333fa5852R429

**Comment by lamont-granquist** [comment]
can you use or can test-kitchen be modified to use extended length paths with the "\\?\" prefix?

**Comment by jkerry** [comment]
I might be misunderstanding the question but the limit is really at the windows OS level.  260 characters is the max before the OS shuts you down.

**Comment by jkerry** [comment]
an example of a path generated too long for windows:
`C:\Jenkins\workspace\PRTests\XXXXX_one-cookbook-pr\cookbooks\aloha_one\.kitchen\kitchen-vagrant\kitchen-XXXXX_one-default-windows-2012r2\kitchen-XXXXX_one-default-windows-2012r2_default_1503316491808_83138\kitchen-aloha_one-default-windows-2012r2_default_1503316491808_83138.vbox`

**Comment by jkerry** [comment]
a substring or a digest on 1503316491808_83138 might be feasible.  It looks like default made it into the path twice.

**Comment by robbkidd** [comment]
Could we omit `kitchen-#{something_unique}-` from the vagrant root entirely? That would yield:

```
C:\Jenkins\workspace\PRTests\XXXXX_one-cookbook-pr\cookbooks\XXXXX_one\.kitchen\kitchen-vagrant\default-windows-2012r2\default-windows-2012r2_default_1503316491808_83138\default-windows-2012r2_default_1503316491808_83138.vbox
```

One consequence: machines listed in the hypervisor would not have `kitchen-#{something_unique}-` prefixed in their names.

**Comment by robbkidd** [comment]
Proposed fix (omit `kitchen-#{basename(kitchen_root)}-` from `vagrant_root`) submitted over on #323.
