### ISSUE TITLE
New release of gem

### ISSUE THREAD

**Issue by bheuvel** [test-kitchen/kitchen-vagrant#213]
Would someone mind making a new Gem release?

For me/us it would release #167 (improved) CloudStack support.
Perhaps there are not many other features to warrant a release, but therefore waited already several months before making this request.

Then again, at this rate may take a year before enough features are in to deserve a release :smile: 
So, as making a gem release is also not that big a deal, perhaps someone (@fnichol ?) would be so kind to make a release?

**Comment by cheeseplus** [comment]
We're not necessarily holding it back for the sake of features and there is a whole batch of new maintainers so this should be coming soon. We're having a meeting today and this is at the top of the list.

**Comment by bheuvel** [comment]
Thanks @cheeseplus ! Great to hear it's comming soon!

**Comment by bheuvel** [comment]
@cheeseplus, not to be pushy :innocent:, but what release date/schedule was decided in the meeting you had?

**Comment by cheeseplus** [comment]
Done @67a5248

**Comment by bheuvel** [comment]
@cheeseplus cool! Thanks!
