### ISSUE TITLE
Support for Vagrant file provisioner feature

### ISSUE THREAD

**Issue by EricsonMacedo** [test-kitchen/kitchen-vagrant#216]
The Vagrant file provisioner feature described in the following [link](https://www.vagrantup.com/docs/provisioning/file.html) is not supported by the default Vagrantfile.erb in Kitchen::Vagrant. As a Kitchen::Vagrant user I would like to have support for the file provisioner feature and a new entry for it in the README.md.

**Comment by cheeseplus** [comment]
Is using a custom `vagrantfile_erb` out of the question? I'm open to adding features but this is a little bit outside the core wheelhouse of TK and we've got the existing facility I've mentioned.

**Comment by EricsonMacedo** [comment]
As you mentioned I can have the Vagrant file provisioner feature through a custom `vagrantfile_erb`, but I need to provide this custom `vagrantfile_erb` every time I need to just have a straight forward copy of a file or a folder from the host machine to the vm box. I believe this feature would be best suited as an out of the box solution from the Kitchen::Vagrant master branch instead of a feature possible after an undocumented customization of the `vagrantfile_erb` and giving the [warning](https://github.com/test-kitchen/kitchen-vagrant#-vagrantfile_erb) presented in the main README.md this would scary newcomers to try or think about this.

**Comment by mwrock** [comment]
What about using `synced_folders`? That should make files on the host reachable to the guest and is built in to vagrant and this driver.

**Comment by cheeseplus** [comment]
@EricsonMacedo the warning in the Readme shouldn't scare you off too much as cookbooks usually have the vagrantfile.erb bundled with them. That said, this is a fine feature to add and we'd happily review a PR but currently not a high priority given there is a documented workaround.

Note: all vagrantfile_erb customizations are documented but that's Vagrant's documentation not ours

**Comment by cheeseplus** [comment]
Upon review using `shared_folders` with rsync or a custom `vagrantfile_erb` solves this more than adequately without pushing kitchen-vagrant into mirroring _every_ single upstream option which is something we explicitly avoid (when possible).
