### ISSUE TITLE
Problem with run command Kitchen Test

### ISSUE THREAD

**Issue by lelix** [test-kitchen/kitchen-vagrant#225]
```
lelixone@Star:~/diego/kitchen-salt-tutorial/beaver-formula$ kitchen test
-----> Starting Kitchen (v1.2.1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'vagrant' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by cheeseplus** [comment]
How are you running test-kitchen? If you are running via your own gems then you will need to install dependencies like kitchen-vagrant yourself or via bundeler.

If you are using ChefDK this is already taken bundled.

**Comment by lelix** [comment]
i used chefdk, I need to remove test-kitchen on GemFile?

**Comment by cheeseplus** [comment]
If you have ChefDK installed and properly in the path then kitchen-vagrant should already be installed - by the version of Kitchen I see you using, that is rather old. Current test-kitchen in ChefDK 0.12.0 is 1.6.0 and version 1.7.3 was released a few days ago.

If you are using ChefDK and also using bundler via a Gemfile then you are responsible for declaring dependencies yourself.

**Comment by lelix** [comment]
Thanks Bro, you helped me, I removed from the Gemfile test-kitchen and problem resolved for me

**Comment by cheeseplus** [comment]
Awesome! Glad it's working for you.
