### ISSUE TITLE
Problem with run command Kitchen Test

### ISSUE THREAD

**Issue by lelix** [test-kitchen/kitchen-vagrant#226]
Script running, but an error occurs

`-----> Installing Serverspec..
Fetching: sfl-2.2.gem (100%)
Fetching: net-telnet-0.1.1.gem (100%)
Fetching: net-ssh-3.1.1.gem (100%)
Fetching: net-scp-1.2.1.gem (100%)
Fetching: specinfra-2.57.0.gem (100%)
Fetching: rspec-support-3.4.1.gem (100%)
Fetching: diff-lcs-1.2.5.gem (100%)
Fetching: rspec-expectations-3.4.0.gem (100%)
Fetching: rspec-core-3.4.4.gem (100%)
Fetching: rspec-its-1.2.0.gem (100%)
Fetching: rspec-mocks-3.4.1.gem (100%)
Fetching: rspec-3.4.0.gem (100%)
Fetching: multi_json-1.11.3.gem (100%)
Fetching: serverspec-2.32.0.gem (100%)
-----> serverspec installed (version 2.32.0)
       /opt/chef/embedded/bin/ruby -I/tmp/verifier/suites/serverspec -I/tmp/verifier/gems/gems/rspec-support-3.4.1/lib:/tmp/verifier/gems/gems/rspec-core-3.4.4/lib /opt/chef/embedded/bin/rspec --pattern /tmp/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /tmp/verifier/suites/serverspec
       /tmp/verifier/suites/serverspec/beaver_spec.rb:3:in `<top (required)>': uninitialized constant Serverspec::Helper::Exec (NameError)
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
       	from /opt/chef/embedded/bin/rspec:22:in `load'
       	from /opt/chef/embedded/bin/rspec:22:in `<main>'
/opt/chef/embedded/bin/ruby -I/tmp/verifier/suites/serverspec -I/tmp/verifier/gems/gems/rspec-support-3.4.1/lib:/tmp/verifier/gems/gems/rspec-core-3.4.4/lib /opt/chef/embedded/bin/rspec --pattern /tmp/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /tmp/verifier/suites/serverspec failed
       !!!!!! Ruby Script [/tmp/verifier/gems/gems/busser-serverspec-0.5.9/lib/busser/runner_plugin/../serverspec/runner.rb /tmp/verifier/suites/serverspec] exit code was 1
```
>>>>>> Verify failed on instance <default-ubuntu-1204>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1204.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '
```

BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE

sudo -E /tmp/verifier/bin/busser test
']
```
>>>>>> ----------------------
zlib(finalizer): the stream was freed prematurely.
```
`

**Comment by lelix** [comment]
```
lelixone@Star:~/diego/kitchen-salt-tutorial/beaver-formula$ chef -v
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: ERROR

```

**Comment by lelix** [comment]
```
-----> Running serverspec test suite
       /opt/chef/embedded/bin/ruby -I/tmp/verifier/suites/serverspec -I/tmp/verifier/gems/gems/rspec-support-3.4.1/lib:/tmp/verifier/gems/gems/rspec-core-3.4.4/lib /opt/chef/embedded/bin/rspec --pattern /tmp/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /tmp/verifier/suites/serverspec
       /tmp/verifier/suites/serverspec/beaver_spec.rb:3:in `<top (required)>': uninitialized constant Serverspec::Helper::Exec (NameError)
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
       	from /tmp/verifier/gems/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
       	from /opt/chef/embedded/bin/rspec:22:in `load'
       	from /opt/chef/embedded/bin/rspec:22:in `<main>'
       /opt/chef/embedded/bin/ruby -I/tmp/verifier/suites/serverspec -I/tmp/verifier/gems/gems/rspec-support-3.4.1/lib:/tmp/verifier/gems/gems/rspec-core-3.4.4/lib /opt/chef/embedded/bin/rspec --pattern /tmp/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /tmp/verifier/suites/serverspec failed
       !!!!!! Ruby Script [/tmp/verifier/gems/gems/busser-serverspec-0.5.9/lib/busser/runner_plugin/../serverspec/runner.rb /tmp/verifier/suites/serverspec] exit code was 1
>>>>>> Verify failed on instance <default-ubuntu-1204>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1204.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE

sudo -E /tmp/verifier/bin/busser test
']
>>>>>> ----------------------
zlib(finalizer): the stream was freed prematurely.

```

**Comment by cheeseplus** [comment]
You should need `set :backend, :exec` in the spec_helper.rb

**Comment by lelix** [comment]
i add `set :backend, :exec ` in the spec_helper.rb
but I got a new error

```
           default: Guest Additions Version: 5.0.16
           default: VirtualBox Version: 4.3
       ==> default: Setting hostname...
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [SSH] Established
       Vagrant instance <default-ubuntu-1204> created.
       Finished creating <default-ubuntu-1204> (0m43.64s).
-----> Converging <default-ubuntu-1204>...
       Preparing files for transfer
       Preparing salt-minion
       Preparing state_top
       Preparing pillars into /srv/pillar
       Preparing formula: beaver from /home/lelixone/diego/kitchen-salt-tutorial/beaver-formula
       Preparing formula: Gemfile.lock.back from /home/lelixone/diego/kitchen-salt-tutorial/beaver-formula/
       Preparing formula: top.sls from /home/lelixone/diego/kitchen-salt-tutorial/beaver-formula/
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [File exists @ dir_s_mkdir - /tmp/default-ubuntu-1204-sandbox-20160426-7226-dsoary/srv/salt/top.sls]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

zlib(finalizer): the stream was freed prematurely.

```

**Comment by mwrock** [comment]
A brief look at your output seems to indicate you are using a salt provisioner. Not sure the exact provisioner but you may get better support by addressing these issues in the repo that owns that provisioner.

**Comment by lelix** [comment]
I follow the instructions 
[https://github.com/simonmcc/kitchen-salt/blob/master/INTRODUCTION.md]

**Comment by jjasghar** [comment]
@lelix It looks like the last time that doc was written to was 2014. It's safe to say that TK has made leaps and bounds since then. It's very possible that kitchen-salt isn't compatible with the changes we've made.

**Comment by mwrock** [comment]
I'm going to close this issue and recommend opening a issue in that repo. It does look like an active repo. Last commit was 21 days ago.

**Comment by lelix** [comment]
@mwrock ok
