### ISSUE TITLE
Ubuntu 16.04 box

### ISSUE THREAD

**Issue by Vrtak-CZ** [test-kitchen/kitchen-vagrant#227]
Please add Ubuntu 16.04 box.

**Comment by jjasghar** [comment]
@Vrtak-CZ https://github.com/chef/bento/pull/545? Is that what you're asking for?

**Comment by cheeseplus** [comment]
@Vrtak-CZ this is related to bento, the issue doesn't belong here so I'm closing.

We are currently working on builds but all the vmtools for each provider are fundamentally broken so shared folders are also broken.

**Comment by Vrtak-CZ** [comment]
@jjasghar thank you! That's it!
