### ISSUE TITLE
add option to create new box or snapshot if verify passes, converge with snapshot

### ISSUE THREAD

**Issue by sanguis** [test-kitchen/kitchen-vagrant#229]
Sometimes development on a box can last more than one or two sprints/sessions.  It would  be great to be have a function to add a new box or a way to add a snapshot after verify passes. That way when I continue my work I don't have to converge from scratch at the beginning of every session.

**Comment by cheeseplus** [comment]
There is a top-level `package` subcommand in test-kitchen core that already exists - this would need to be wired up in kitchen-vagrant.

**Comment by n-rodriguez** [comment]
https://github.com/test-kitchen/kitchen-vagrant/pull/275

**Comment by cheeseplus** [comment]
This was completed by #275
