### ISSUE TITLE
Bug in box_check_update code

### ISSUE THREAD

**Issue by rayterrill** [test-kitchen/kitchen-vagrant#237]
The "box_check_update" section of code in templates/Vagrantfile.erb is resulting in the quoted value of whatever you've entered (true/false) to be transferred to the Vagrantfile, and it isn't working correctly (i.e. false becomes "false", which is not the same as false).

```
<% if !config[:box_check_update].nil? %>
  c.vm.box_check_update = "<%= config[:box_check_update] %>"
<% end %>
```

Validated that removing the quotes from the Vagrantfile manually results in the correct behavior in Vagrant - it no longer checks for an updated box on a 'vagrant up'. This is probably just as simple as removing the quotes, like:

```
<% if !config[:box_check_update].nil? %>
  c.vm.box_check_update = <%= config[:box_check_update] %>
<% end %>
```

Backstory: We're behind a proxy and using Windows, so these kind of things kill us. :(

**Comment by mwrock** [comment]
I totally get the `"false" != false` but it strikes me as weird that this ever worked. Looking through history this was edited a year ago by @roderickrandolph via #182 to make sure `false` made it in.

**Comment by rayterrill** [comment]
Also not sure how this ever worked. Also apologies - I'm a GitHub n00b (this was my first ever PR!) so my fault if I messed something up or not understanding how something works.

I manually made this change today in my local machine's Vagrantfile.erb because this is killing me, and things are working as expected.

**Comment by jjasghar** [comment]
@rayterrill congrats on your first PR! Don't worry everyone is a beginner at some point; and we all gain experience at different rates. 

Welcome and please continue to contribute, we are all better because you are here.

**Comment by mwrock** [comment]
:+100: to what @jjasghar said

**Comment by mwrock** [comment]
See im still learning to emoticon!

**Comment by rayterrill** [comment]
Thanks all!
