### ISSUE TITLE
Vagrant doesn't like the new cache shared folder feature

### ISSUE THREAD

**Issue by Annih** [test-kitchen/kitchen-vagrant#250]
Hello,

Following update to kitchen-vagrant `0.21.0` my test-kitchen suites are failing on windows platform with the below error message:
> ---- Begin output of vagrant up --no-provision --provider virtualbox ----
> STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
> STDERR: There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> 
> vm:
> * The shared folder guest path must be absolute: $env:TEMPomnibusche
> ---- End output of vagrant up --no-provision --provider virtualbox ----

It seems due to a check in vagrant ensuring [shared folder path is aboslute](https://github.com/mitchellh/vagrant/blob/v1.9.0/plugins/kernel_v2/config/vm.rb#L646)

Our vagrant and Gems' versions are:
* vagrant 1.8.1
* test-kitchen 1.14.0
* kitchen-vagrant 0.21.0

I'm sorry I have no time to dig more, thanks in advance to have a look to this issue, in the meantime I'll just change my constraint on `kitchen-vagrant` to exclude release `0.21.0`

**Cc.** @aboten

**Comment by cheeseplus** [comment]
Thanks for the report, while we look into that I'd also note that Vagrant version is fairly old - Vagrant 1.9.0 just released.

**Comment by afiune** [comment]
@Annih I second Cheeseplus. Thank you for reporting this. We are currently working on this problem. We will keep you posted!

**Comment by afiune** [comment]
@Annih We are about to release a new gem. *v.0.21.1* should fix your problem! 👍

**Comment by kamaradclimber** [comment]
thanks @afiune !
