### ISSUE TITLE
Windows: The shared folder guest path must be absolute: $env:TEMPomnibusche

### ISSUE THREAD

**Issue by bheuvel** [test-kitchen/kitchen-vagrant#256]
Problems occurs on 0.21.0.
Problem does NOT occur on 0.20.0

When provisioning a Windows VM, errors out on:
```
-----> Creating <default-windows2012>...
       There are errors in the configuration of this machine. Please fix
       the following errors and try again:
       
       vm:
       * The shared folder guest path must be absolute: $env:TEMPomnibusche
```

(Part of) Resulting Vagrantfile:
```
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "Win2012R2DC-x86_64"
  c.vm.communicator = "winrm"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/bheuvel/.kitchen/cache", "$env:TEMP\omnibus\cache", create: true
  c.vm.provider :cloudstack do |p|
    p.host = "XXXXXXXXXXXXXXXXX"
    p.path = "/client/api"
    p.port = 443
<snip>
    p.expunge_on_destroy = true
  end
end
```

Version 0.21.0 introduces the problematic line: 
```c.vm.synced_folder "/Users/bheuvel/.kitchen/cache", "$env:TEMP\omnibus\cache", create: true```

**Comment by kernelsmith** [comment]
I'm also encountering this error, except for me the generated Vagrantfile lacks the slashes entirely, the classic ruby strings vs windows file path issue

**Comment by afiune** [comment]
@bheuvel Thank you for reporting this issue, we have fixed this problem and we are now in the process of releasing a new gem. If you want to try it you can always use the latest code in master this repository.

**Comment by bheuvel** [comment]
@afiune thanks! 👍
