### ISSUE TITLE
Changing synced folders owner and group

### ISSUE THREAD

**Issue by wasimkham** [test-kitchen/kitchen-vagrant#265]
I cannot seem to figure out how to change the owner and group of a synced folder. I've tried the following but they all result in syntax errors.

```
synced_folders:
        - ["../../web", "/var/www", "create: true, owner: :vagrant, group: :www-data"]

synced_folders:
        - ["../../web", "/var/www", "create: true, owner: "vagrant", group: "www-data""]
```

I cannot find anything in the docs about changing ownership, or even just changing the permissions would be enough.

Appreciate the help.

**Comment by cheeseplus** [comment]
Closing due to lack of response.
