### ISSUE TITLE
VMware Workstation path too long

### ISSUE THREAD

**Issue by neilfrawley** [test-kitchen/kitchen-vagrant#267]
When I use Test Kitchen 1.14.2, Vagrant 1.8.5, VMware Workstation 12.0.0 and the vagrant-vmware-workstation 4.0.15 plugin.

The virtual machines are created in a folder inside my local Chef cookbook repository.
e.g.
C:\_cookbookname_\.kitchen\kitchen-vagrant\kitchen-_cookbookname-__suitename-platformname_\.vagrant\machines\default\vmware_workstation\<long-random-string\filename.vmx

When VMware Workstation attempts to start the virtual machine in this folder, it fails because the path is too long. I can copy the folder containing the virtual machine to a shorter path and successfully start the virtual machine.

Can the kitchen-vagrant driver be changed to use the default location for virtual machines in VMware Workstation as the folder where the virtual machine files are created? 
This would mirror how it works with Oracle VirtualBox.

**Comment by carlosaya** [comment]
This n00b never heard of the VAGRANT_VMWARE_CLONE_DIRECTORY environmental variable.  This is what happens when I take the day off.  ; )

**Comment by neilfrawley** [comment]
Thanks, I can confirm that works. 
I set that environment variable to a folder with a short path. 

Then I use the following option in the .kitchen.yml file
_driver:
  name: vagrant
  gui: true
  provider: vmware_workstation
  **linked_clone: true**_
