### ISSUE TITLE
Issue creating default cache directory mount on mac osx

### ISSUE THREAD

**Issue by brentm5** [test-kitchen/kitchen-vagrant#280]
Not 100% sure if this is the same as #199 but I do not think it is the case.  I was trying to run a macosx virtual box image and everything worked except for the default cache directory:

```
==> default: Mounting shared folders...
    default: /tmp/omnibus/cache => /Users/brentm5/.kitchen/cache
Vagrant is not able to mount VirtualBox shared folders on BSD-based
guests. BSD-based guests do not support the VirtualBox filesystem at
this time.

To change the type of the default synced folder, specify the type as
rsync or nfs:

    config.vm.synced_folder ".", "/vagrant", type: "nfs" # or "rsync"

Alternatively, if you do not need to mount the default synced folder,
you can also disable it entirely:

    config.vm.synced_folder ".", "/vagrant", disabled: true

You can read more about Vagrant's synced folder types and the various
configuration options on the Vagrant website.

This is not a bug in Vagrant.
```

I was able to get around this by following the directions [here](https://github.com/test-kitchen/kitchen-vagrant#-synced_folders) however I had to set the cache directory to false in order to make that work.  Not sure if osx hosts should be included in the following snippet considering they are a variant of BSD I believe

https://github.com/test-kitchen/kitchen-vagrant/blob/master/lib/kitchen/driver/vagrant.rb#L219-L227

**Comment by cheeseplus** [comment]
macOS/OSX needs to be excluded just the same
