### ISSUE TITLE
Hyper-V Documentation

### ISSUE THREAD

**Issue by michaeltlombardi** [test-kitchen/kitchen-vagrant#298]
Currently, this plugin explicitly lists a few vagrant providers it works with, but does not include Hyper-V - even though Hyper-V vagrant boxes **do** work with this plugin.

## Expected Behavior
Users reading the documentation for `kitchen-vagrant` should see that Hyper-V vagrant boxes are a supported option and be able to read specific documentation around possible pitfalls and workarounds.

## Current Behavior
Hyper-V is not mentioned at all, though a list of supported providers is given.

## Possible Solution
Update the documentation to reflect Hyper-V as an option and how to resolve some necessary workarounds (such as selecting a specific virtual switch to avoid a hung session).

## Context
Hyper-V is now a fully supported vagrant provider and should be supported in this plugin, especially since it already works!

## Environment
* Vagrant Version: `1.9.2`
* Operating System: Windows `10.0.14393`
* PowerShell Version: `5.1.14393.693`
* Test-Kitchen Version: `1.15.0`
* Chef Development Kit Version: `1.2.22`
* Chef-Client version: `12.18.31`

**Comment by michaeltlombardi** [comment]
This was generated from the exploration in #297.

**Comment by cheeseplus** [comment]
@michaeltlombardi could you open up a PR to add this based on #297? That'd be ideal as I don't have a Hyper-V setup readily available so would love to have this done by someone who has validated it.

**Comment by cheeseplus** [comment]
Closed by https://github.com/test-kitchen/kitchen-vagrant#hyper-v
