### ISSUE TITLE
Officially support vagrant-libvirt

### ISSUE THREAD

**Issue by kivoli** [test-kitchen/kitchen-vagrant#311]
While the vagrant-libvirt plugin may not be an official Vagrant provider it is probably the largest unofficial one with some Debian maintainers even providing semi-official [Debian boxes](https://app.vagrantup.com/debian) for it.

While it is not listed in the [README.md](https://github.com/test-kitchen/kitchen-vagrant/blob/master/README.md) there is actually a tiny bit of code specific to libvirt in the code base already. So far I have not had any issues with this provider and wonder why it’s not listed, at least as “not maintained” but technically supported. Before opening a PR to enhance the README accordingly I wanted to get the maintainers’ general stance on this topic.

**Comment by cheeseplus** [comment]
You're welcome to add something to the wiki or readme but as it stands "unofficially" supported drivers all fall into the same bucket. We'll merge PRs or request around these in so much as it doesn't break anything existing. This doesn't make it any more supported from our perspective but will allow folks to work with it.

The catch here is that as we don't build boxes in bento for libvirt, it's not something we're using internally or advocating people use so if it breaks it's fairly low priority for us as maintainers. It's not unlisted for any specific reason other than it falls into the "other" bucket which includes a whole host of vagrant options that may or may not work and we merely pass through.

So this really depends on what you want "officially" to mean here - if you'd like to add additional documentation for libvirt users we'd definitely accept it and it probably works well as a wiki page.
