### ISSUE TITLE
Kitchen-salt hangs on sudo command

### ISSUE THREAD

**Issue by alem0lars-yoroi** [test-kitchen/kitchen-vagrant#314]
I've already used kitchen-vagrant in the past, and I didn't get any of the following errors.
So probably, if confirmed, is a bug due to recent codebase changes.

After **the first time** I run `bundle exec kitchen converge`, it gets stuck while executing:

```
bash -c sudo -E chmod +x /tmp/kitchen/*.sh;sudo -E /tmp/kitchen/dependencies.sh;sudo -E salt-call --state-output=changes --config-dir=/tmp/kitchen/etc/salt --local state.highstate --retcode-passthrough
```

The problematic part (the one that hangs) is the first one using `sudo` (=> `sudo -E /tmp/kitchen/dependencies.sh`).

I've tried to comment out that line, replacing it with a `echo` and it works.

I don't know what's the cause but I guess the reason could be the process is stuck asking for sudo password (that should be `vagrant`).

Also, I dig into the sourcecode of kitchen-vagrant and test-vagrant and I couldn't find where it is set.

Could you help me in this issue?

Thanks.

**Comment by cheeseplus** [comment]
The `sudo_command` is handled by core test-kitchen and provisioners inherit this - https://github.com/test-kitchen/test-kitchen/blob/f8f87b8df62ce53aecfb6a1af977fc74daeaa0df/lib/kitchen/provisioner/base.rb#L44.

Setting that value to your desired sudo incantation should work.

**Comment by alem0lars-yoroi** [comment]
Thanks :+1:
