### ISSUE TITLE
Issue with kitchen on Windows 10

### ISSUE THREAD

**Issue by emo3** [test-kitchen/kitchen-vagrant#331]
I have Hyper-V disabled
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1
git version 2.14.2.windows.1
vboxmanage version 5.1.28r117968
Vagrant 2.0.0
.kitchen.yml >>
---
driver:
  name: vagrant
provisioner:
  name: chef_zero
verifier:
  name: inspec
platforms:
  - name: centos-7.3
suites:
  - name: default
    run_list:
      - recipe[learn_chef_httpd::default]
<<
mydir@MINGW64 ~/chef/cookbooks/learn_chef_httpd (master)
$ kitchen create -l debug
-----> Starting Kitchen (v1.17.0)
D      [Vagrant command] BEGIN (vagrant --version)
D      [Vagrant command] END (0m0.00s)
D      Berksfile found at C:/Users/mydir/chef/cookbooks/learn_chef_httpd/Berksfile, loading Berkshelf
D      Berkshelf 6.3.1 library loaded
-----> Creating <default-centos-73>...
D      <default-centos-73> is synchronizing on Kitchen::Driver::Vagrant#create
D      <default-centos-73> is messaging Kitchen::Driver::Vagrant#create
D      Creating Vagrantfile for <default-centos-73> (C:/Users/mydir/chef/cookbooks/learn_chef_httpd/.kitchen/kitchen-vagrant/default-centos-73/Vagrantfile)
D      ------------
D      Vagrant.configure("2") do |c|
D        c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
D        c.vm.box = "bento/centos-7.3"
D        c.vm.hostname = "default-centos-73.vagrantup.com"
D        c.vm.synced_folder ".", "/vagrant", disabled: true
D        c.vm.synced_folder "C:/Users/mydir/.kitchen/cache", "/tmp/omnibus/cache", create: true
D        c.vm.provider :virtualbox do |p|
D        end
D      end
D      ------------
D      [Vagrant command] BEGIN (vagrant up --no-provision --provider virtualbox)
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'bento/centos-7.3'...
==> default: Matching MAC address for NAT networking...
       ==> default: Checking if box 'bento/centos-7.3' is up to date...
       ==> default: Setting the name of the VM: default-centos-73_default_1506908515718_52845
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 (guest) => 2222 (host) (adapter 1)
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2222
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: Warning: Connection aborted. Retrying...
           default: Warning: Remote connection disconnect. Retrying...
           default: Warning: Connection reset. Retrying...
           default: Warning: Connection aborted. Retrying...
           default: Warning: Connection reset. Retrying...
           default: Warning: Connection aborted. Retrying...
           default: Warning: Connection reset. Retrying...
           default:
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default:
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Mounting shared folders...
           default: /tmp/omnibus/cache => C:/Users/mydir/.kitchen/cache
       ==> default: Machine not provisioned because `--no-provision` is specified.
D      [Vagrant command] END (0m0.00s)
D      [Vagrant command] BEGIN (vagrant ssh-config)
D      [Vagrant command] END (0m0.00s)
D      [SSH] opening connection to vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2222", :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/c/Users/mydir/chef/cookbooks/learn_chef_httpd/.kitchen/kitchen-vagrant/default-centos-73/.vagrant/machines/default/virtualbox/private_key"], :auth_methods=>["publickey"]}>
D      [SSH] connection failed (#<Net::SSH::AuthenticationFailed: Authentication failed for user vagrant@127.0.0.1>)
       Waiting for SSH service on 127.0.0.1:2222, retrying in 3 seconds
D      [SSH] opening connection to vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2222", :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/c/Users/mydir/chef/cookbooks/learn_chef_httpd/.kitchen/kitchen-vagrant/default-centos-73/.vagrant/machines/default/virtualbox/private_key"], :auth_methods=>["publickey"], :logger=>#<Logger:0x0000000006ce58c8 @level=4, @progname=nil, @default_formatter=#<Logger::Formatter:0x0000000006ce5850 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x0000000006ce57b0 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x0000000006ce5738>>>, :password_prompt=>#<Net::SSH::Prompt:0x0000000006ce5710>, :user=>"vagrant"}>
D      [SSH] connection failed (#<Net::SSH::AuthenticationFailed: Authentication failed for user vagrant@127.0.0.1>)
       Waiting for SSH service on 127.0.0.1:2222, retrying in 3 seconds
D      [SSH] opening connection to vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2222", :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/c/Users/mydir/chef/cookbooks/learn_chef_httpd/.kitchen/kitchen-vagrant/default-centos-73/.vagrant/machines/default/virtualbox/private_key"], :auth_methods=>["publickey"], :logger=>#<Logger:0x0000000006ce58c8 @level=4, @progname=nil, @default_formatter=#<Logger::Formatter:0x0000000006ce5850 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x0000000006ce57b0 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x0000000006ce5738>>>, :password_prompt=>#<Net::SSH::Prompt:0x0000000006ce5710>, :user=>"vagrant"}>
D      [SSH] connection failed (#<Net::SSH::AuthenticationFailed: Authentication failed for user vagrant@127.0.0.1>)
       Waiting for SSH service on 127.0.0.1:2222, retrying in 3 seconds
^C

$ cd .kitchen/kitchen-vagrant/default-centos-73/
$ vagrant ssh-config
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /c/Users/mydir/chef/cookbooks/learn_chef_httpd/.kitchen/kitchen-vagrant/default-centos-73/.vagrant/machines/default/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL

$ vagrant ssh
[vagrant@default-centos-73 ~]$

So how do I fix kitchen to work?
BTW: This same code works on my mac running sierra

**Comment by kvecchione** [comment]
I saw this issue as well. Dropped my vagrant version down to 1.8.6 as a test and it worked.

**Comment by emo3** [comment]
This is a bug in 2.0.0, 1.9.8 worked.
Thanks @kvecchione

**Comment by morrell** [comment]
Also having this issue with vagrant 2.0

**Comment by tpetchel** [comment]
I was able to verify that things fail on Windows 10: https://gist.github.com/tpetchel/f186f94572fb510a5a5398dd79f5db7b

Setup:
* Vagrant 2.0.0
* VirtualBox 5.1.30r118389
* Box: bentos/centos-7
* Chef DK 2.3.4
* kitchen-vagrant 1.2.1

I also verified that things work as expected from macOS 10.12 and Ubuntu 16.04.

**Comment by emo3** [comment]
now works with:
git version 2.15.0.windows.1
Vagrant 2.0.1
vboxmanage 5.2.0r118431

**Comment by cheeseplus** [comment]
Unfortunately 2.0.1 breaks MacOS. Either way, this isn't a kitchen-vagrant issue so closing.

**Comment by emo3** [comment]
The same versions are on my mac, and I do not have issues.
