### ISSUE TITLE
Start VM if one exists but is currently shut down

### ISSUE THREAD

**Issue by Nowaker** [test-kitchen/kitchen-vagrant#337]
Problem: when a Vagrant VM exists but is currently shut down, Kitchen/Vagrant driver will try to connect to it unsuccessfully, and fail.

```
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::AuthenticationFailed: Authentication failed for user vagrant@127.0.0.1>)
```

Calling `setup` will recreate a VM from scratch.

All that's really needed to start it without spending a ton of time on `setup` and `converge` from scratch is look up the VM name in `.kitchen/kitchen-vagrant/default-ubuntu-1604/.vagrant/machines/default/virtualbox/id`, then start the given VM with `VBoxManage`.

Vagrant driver should check if a VM exists and if it's shut down, just start it.

```
nowaker@nwkr-mbp ..eamhost/gitlab-ci-runner-virtkick-chef (git)-[master] % cat .kitchen/kitchen-vagrant/default-ubuntu-1604/.vagrant/machines/default/virtualbox/id
fb3d95e9-6c7d-427f-ae69-392d1a540110
nowaker@nwkr-mbp ..eamhost/gitlab-ci-runner-virtkick-chef (git)-[master] % VBoxManage list  vms|grep fb3d95e9-6c7d-427f-ae69-392d1a540110
"default-ubuntu-1604_default_1511988450113_8085" {fb3d95e9-6c7d-427f-ae69-392d1a540110}
nowaker@nwkr-mbp ..eamhost/gitlab-ci-runner-virtkick-chef (git)-[master] % VBoxManage startvm "default-ubuntu-1604_default_1511988450113_8085" --type headless
```

(For some reason, `VBoxManage startvm UUID --type headless` didn't work for me)

**Comment by cheeseplus** [comment]
We have a mantra "kitchen is not a virtual machine management utility"

The problem here is that this entirely breaks the abstraction we've setup, forcing us to call out to vBoxManage directly (which is only one supported provider, though default). If you want to work with a machine as an interactive VM then using Vagrant directly is the better option.

That is to say, this isn't something we're super keen on adding as it's just gold plating on a side affect - moreover this gets even less appealing the more providers you consider we support.

**Comment by MarkGibbons** [comment]
I don't have great evidence for what I'm going to write.  I run into what I think is a version of the OP's problem on a daily basis.

At some point in the last few years virtual box started automatically powering down boxes.  So a work flow might look like this.

- start new work
- kitchen converge (create, converge)
- go away for a while box does an auto shutdown.
- kitchen converge or verify - fails even though the box exists
- kitchen create -starts box without creating a new instance
- continue working

Most of the new users I see doing this get horribly confused.  The box exists but they can't use it.  They want to test a change so they delete the server. I've seen multiple people do kitchen delete after every converge just to make things predictable.  That kitchen create does something to start the box back up tells me the code to fix this is already there.

thanks,
  Mark

**Comment by Nowaker** [comment]
@cheeseplus, well, why use Vagrant directly if Kitchen does everything I want? 😀 It's so great I'd be a fool not to use it! (Thanks for all your work!) Starting/resuming a VM that's off at a time is just a small improvement to an existing solution - not really a feature. And yes, @MarkGibbons is right here, that was exactly the issue I was getting, VMs were stopped at some point for no apparent reason. Quite confusing at first, and time consuming to repeat the setup stage for no real reason.

@MarkGibbons I'd rather `setup` do just that - setup a new VM. Kitchen CI should attempt to start VM for converge/verify if VM is created but off. But these are just semantics. Thanks for joining the discussion!

**Comment by coderanger** [comment]
What do you mean by "box does an auto shutdown"? That isn't something we are setting up, and should be disabled if we left it on accidentally.

**Comment by Nowaker** [comment]
I guess VirtualBox has some sort of out-of-memory watch and shuts down machines when needed. With 8 GB RAM on a typical MBP, this must be happening often.

**Comment by MarkGibbons** [comment]
Auto shutdown - after server power drops to some % turn off the boxes has been reported.  Seems like boxes are shut down after some time limit.  It's not something test kitchen does, I think it's a virtual box function and generally it's a good thing.  I've never followed up enough on why it happens.

**Comment by cheeseplus** [comment]
Pretty sure this is a low power condition on laptops causing the auto-shutdown and can be configured a la 

```
VBoxManage setextradata global "VBoxInternal2/SavestateOnBatteryLow" 0
```

The reason that `create` works is probably because it runs `vagrant up` which will do the necessary thing. Because of how the components in kitchen and segregated, kitchen's reasonable expectation is that the transport is up when the last thing you did was create/converge - the same would apply to verify. It's not quite as simple as re-using that code elsewhere as kitchen core has no notion/hook for "resuming instance from shutdown state' nor do the drivers because of the barrel of monkeys that presents.

**Comment by Nowaker** [comment]
@cheeseplus Thanks for this. I disabled it. This particular aspect should improve with this.

That being said, I still wish "resuming instance from shutdown state" was a possibility. A VM for each cookbook one works on is typically 2 GB RAM. With 8 GB RAM in a typical MBP, it's still not great for productivity - at most, one can work on two cookbooks at a time.

**Comment by cheeseplus** [comment]
That particular limitation comes with the territory with Vagrant and also why there are other drivers that use less memory a la kitchen-dokken or drivers that don't happen on the local box a la kitchen-ec2. It's not that we couldn't optimize it more so much as that's always going to be a chase/issue depending on a person's machine.
