### ISSUE TITLE
c.vm.box configuration incorrectly set for bento/hardenedbsd-11 in generated Vagrantfile

### ISSUE THREAD

**Issue by nusenu** [test-kitchen/kitchen-vagrant#349]
kitchen-vagrant creates the following box line in the Vagrant file when using "- name: hardenedbsd-11":
```
c.vm.box = "hardenedbsd-11"
```
but it should be:
```
c.vm.box = "bento/hardenedbsd-11"
```
The same problem probably occurs once we add OpenBSD to bento.

https://github.com/test-kitchen/kitchen-vagrant/blob/bbb36bcd4f3e0901abcb3ad6bfc6e6a4b3e46758/spec/kitchen/driver/vagrant_spec.rb#L164
REF:
nusenu/ansible-relayor/issues/155

**Comment by cheeseplus** [comment]
kitchen-vagrant will need to be updated to "know" about any new distros and then this will go away.

**Comment by nusenu** [comment]
Seth Thomas:
> kitchen-vagrant will need to be updated to "know" about any new distros and then this will go away.
> 

is the line I quoted above the correct (and only) place to add the new platforms?

If so I can submit a patch

**Comment by cheeseplus** [comment]
Two places need the change:

the code itself that needs updating
https://github.com/test-kitchen/kitchen-vagrant/blob/master/lib/kitchen/driver/vagrant.rb#L237

the unit test (which you've found)
https://github.com/test-kitchen/kitchen-vagrant/blob/bbb36bcd4f3e0901abcb3ad6bfc6e6a4b3e46758/spec/kitchen/driver/vagrant_spec.rb#L164

Both need to be updated for this to work but it should be an easy PR.
