### ISSUE TITLE
Unreleased fixes for HyperV

### ISSUE THREAD

**Issue by wduncanfraser** [test-kitchen/kitchen-vagrant#353]
Just wanted to check in and see if it would be possible to get the changes from #345 brought into a 1.3.2 release so that it makes it into ChefDK releases. Without ensuring that virtual switch names are quoted, default hyper-v configurations won't work due to an unquoted "Default Switch", which complicates building system/provider agnostic kitchen configurations.

I have built and installed the gem locally and confirmed Hyper-V is working as intended with default configurations.

**Comment by cheeseplus** [comment]
Closed by #356
