### ISSUE TITLE
Question: Do VMs created by vagrantfiles persist between each suite in Test-Kitchen? 

### ISSUE THREAD

**Issue by predatorian3** [test-kitchen/kitchen-vagrant#361]
I am wondering if any infrastructure stood up by an external and included vagrantfile would persist between .kitchen.yml suites? Looking to use something that would store state data between suites/VMs.

**Comment by coderanger** [comment]
No, every suite+platform combo gets its own VM. If you're trying to do some funky cluster testing, we don't currently support that in a friendly way (you would have to manually bodge it in).

**Comment by predatorian3** [comment]
Okay, thank you for clarifying. I wanted to move some of these Vagrantfile driven clusters out into test kitchen. Inside the Vagrantfile they're spinning up a chef-zero server, then bootstrapping the other nodes in the cluster to that for passing state and testing.

This issue can be closed as it has answered my question. Thank you @coderanger

**Comment by coderanger** [comment]
That is definitely not supported. Sorry.
