### ISSUE TITLE
kitchen-vagrant leaves a trail of semi-imported boxes if the instance name already exists

### ISSUE THREAD

**Issue by arthurlogilab** [test-kitchen/kitchen-vagrant#376]
We're running kitchen-vagrant in a CI pipeline (kudos for a great tool that is helping us tremendously). 

Sometimes we bump into : 

```
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/debian-9' is up to date...
STDERR: A VirtualBox machine with the name 'kitchen-default-debian-9' already exists.
Please use another name or delete the machine with the existing
name, and try again.
---- End output of vagrant up --no-provision --provider virtualbox ----
```
So at some point we added the following as the `after_script` (gitlab-runner)  : 
```
after_script:
  # cleanup - in some cases the VM doesn't stop and is not deleted
  - pkill -9 VBoxHeadless
  - vboxmanage unregistervm kitchen-default-debian-9 --delete
```

This seemed to help a bit, but we have a bunch of `debian-9.5-amd64_TIMESTAMP_UUID` filling up the disk (1.4Go at a time). 

```
root@ot-runner-2:/var/home/gitlab-runner/VirtualBox VMs# du -hxs *
1.4G    debian-9.5-amd64_1537863340785_78432
1.4G    debian-9.5-amd64_1537863492364_76610
[snip]
```
I guess this happens when it starts importing and then fails to rename to `kitchen-default-debian-9`

Is there an option to fix this ? Is this a known bug ? Is this a vagrant bug (haven't searched there yet) ?

**Comment by cheeseplus** [comment]
Technically it is a Vagrant problem but I've seen more reports of this lately so not sure if something changed in Vagrant or VirtualBox along the way. The only change we've made along those lines was supposed to be purely for display purposes in #366.

Please provide versions of Vagrant, VirtualBox, and kitchen/ChefDK and we can do some more digging.

**Comment by arthurlogilab** [comment]
@cheeseplus thanks for the response. 

```
ii  virtualbox              5.2.18-dfsg-1~bp amd64            x86 virtualization solution - base binaries
# vagrant --version
Vagrant 2.0.2
# kitchen --version
Test Kitchen version 1.23.2
```

**Comment by reedlaw** [comment]
I'm having the same problem when running as the `gitlab-runner` user. If I run `kitchen create` as a regular user I don't have the issue. I'm using this script to unregister all VMs: 
```
VBoxManage list vms | sed -r 's/^"(.*)".*$/\1/' | xargs -L1 -I {} VBoxManage unregistervm {} --delete
```

**Comment by mrysanek** [comment]
This may not be the cause, but allowed me to discover a different issue - the machine naming (specifically VirtualBox) is not unique when running a CI of a main branch and a PR _at the same time_, where the .kitchen.yml are the same; one of the Jenkins runs will complain:
"INFO interface: error: A VirtualBox machine with the name 'kitchen-<cookbookname>-<suitename>-<platformname>' already exists.  I will open an issue with details.
