### ISSUE TITLE
kitchen create hangs waiting for network switch

### ISSUE THREAD

**Issue by fegonfe** [test-kitchen/kitchen-vagrant#380]
using vagrant with hyperv provider.
kitchen create hangs with this message:
Please choose a switch to attach to your Hyper-V instance
You cannot type any value. It is completely frozen.

using the environment variable KITCHEN_HYPERV_SWITCH does not work either.

**Comment by cheeseplus** [comment]
You'll need to offer some more details as to version and operating system, the instructions here work in Powershell https://github.com/test-kitchen/kitchen-vagrant#hyper-v

**Comment by fegonfe** [comment]
Windows [Version 10.0.17134.345]
kitchen v1.23.2
vagrant 2.2.0

complete output where it hangs:

-----> Creating <default-ubuntu-1604>...
       Bringing machine 'default' up with 'hyperv' provider...
       ==> default: Verifying Hyper-V is enabled...
       ==> default: Verifying Hyper-V is accessible...
           default: Please choose a switch to attach to your Hyper-V instance.
           default: If none of these are appropriate, please open the Hyper-V manager
           default: to create a new virtual switch.
           default:
           default: 1) DockerNAT
           default: 2) Default Switch
           default: 3) External
           default:

**Comment by cheeseplus** [comment]
How have you try to set the environment variable? Have you tried the alternate config I provided above? Can you provide the kitchen.yml config being used?
