### ISSUE TITLE
Use Vagrant WSL user path

### ISSUE THREAD

**Issue by BCarley** [test-kitchen/kitchen-vagrant#383]
## Vagrant on WSL

When using Vagrant in WSL the file location must be run from within the _Windows_ file system otherwise it will throw the following error:
```
       vm:
       * The host path of the shared folder is not supported from WSL. Host
       path of the shared folder must be located on a file system with
       DrvFs type. Host path: /home/<user>/.kitchen/cache
```
Vagrant reads from a environment variable `VAGRANT_WSL_WINDOWS_ACCESS_USER_HOME_PATH` to tell it where to look instead of the home to get around some of these issues (I think).

Currently when using kitchen-vagrant in WSL, the `~/.kitchen/cache` path is hardcoded meaning that vagrant is unable to run.

Ref:
https://www.vagrantup.com/docs/other/wsl.html#vagrant_wsl_disable_vagrant_home

**Comment by cheeseplus** [comment]
As a workaround can disable the caching entirely by setting that to false https://github.com/test-kitchen/kitchen-vagrant#-cache_directory

I'm not sure what you mean by that path is "hardcoded", it's very much mutable but we can still look into this issue.

**Comment by tas50** [comment]
This should be fixed on master and will be released in just a few moments.
