### ISSUE TITLE
Is there any way to set `enable_serial_logging = false` in generated Vagrantfile?

### ISSUE THREAD

**Issue by Nklya** [test-kitchen/kitchen-vagrant#391]
Hello.

I faced a problem when VBoxHeadless consume much cpu on macOS.

I found that setting `enable_serial_logging = false` in generated Vagrantfile solved this problem as described here https://github.com/Varying-Vagrant-Vagrants/VVV/issues/694

Could you please help me, is there any way to set this option in generated Vagrantfile?

**Comment by cheeseplus** [comment]
This issue really shouldn't be biting folks that badly anymore with recent versions of Vagrant and VBox, but if you absolutely needed to set this then creating a custom Vagrantfile template and using `vagrantfile_erb` is the best way to do so https://github.com/test-kitchen/kitchen-vagrant#-vagrantfile_erb

**Comment by Nklya** [comment]
Thank you, I will check it.

**Comment by cheeseplus** [comment]
Here you can see the default we use and you can tweak it by adding a single line https://github.com/test-kitchen/kitchen-vagrant/blob/master/templates/Vagrantfile.erb
