### ISSUE TITLE
define range for vagrant network port forwarding in .kitchen.yml

### ISSUE THREAD

**Issue by jlosito** [test-kitchen/kitchen-vagrant#400]
Is there a way one can define a range of ports to forward in the yaml file? For instance, I would like to forward 8000-9000 from the guest to the host on port 8000-9000.

**Comment by cheeseplus** [comment]
We (kitchen-vagrant) can only do what vagrant does and it doesn't support this as far as I know or have seen https://www.vagrantup.com/docs/networking/forwarded_ports.html

**Comment by jlosito** [comment]
What I've seen some people do is use a for each loop through the list of ports which they forward in the Vagrantfile, but since there's no way to do that in yaml I was wondering if there's any syntax I could use which would translate that.

**Comment by cheeseplus** [comment]
What you want in that case is https://github.com/test-kitchen/kitchen-vagrant#-vagrantfile_erb. We're not going to layer another abstraction on top (we like to keep things 1:1) but this allows you to bring your own template and do whatever you like in it.
