### ISSUE TITLE
Add qemuargs to libvirt section

### ISSUE THREAD

**Issue by cruwe** [test-kitchen/kitchen-vagrant#419]
First, thank you very much for developing kitchen-vagrant and making you effort available to the general public.

## :person_frowning: Problem Statement

The vagrant libvirt provider may be customized with non-specific `qemuargs` to pass generic options.
In my case, that is which file (`/usr/share/OVMF/OVMF_CODE.fd`) to use as firmware `-bios` (for UEFI).

## :grey_question: Possible Solution

The problem may be resolved by a mere eight-liner, which I already use and would be glad to document properly, should you be willing to accept the change.

## :arrow_heading_up: Describe alternatives you've considered

I'll understand entierly  if you would not like to enlarge the code-base for a provider you clearly state you do not support, so I'd like to ask for your "go ahead" or "please, rather not" before proceeding.

In any case, thanks for your software, it has been extremely useful to me in the past years.

**Comment by marcparadise** [comment]
Thanks for opening this @cruwe, and apologies for the long delay in replying to you. If you're still interested and available, we could support you in getting the change merged.

**Comment by marcparadise** [comment]
@cruwe we're going to close this for now, but if you want to open a PR with the change you found that resolves this, please also re-open this issue.
