### ISSUE TITLE
box_auto_prune: true - do not cause an error when an older box is still actively in use on the machine, just wait until the next run to try again

### ISSUE THREAD

**Issue by gaelik** [test-kitchen/kitchen-vagrant#422]
## :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

When running kitchen create, after an upgrade, the purge run will fail if an active virtualbox is using that same box somewhere else on the system due to the y/n prompt produced by vagrant purge

## Version

2.6.0

## Environment

macos, chef workstation 20.8.125

## Scenario

Maybe kitchen create should not fail and just gracefully skip the purge phase, eventually purging the old box when not seen in usage during a future kitchen create run, to not totally break the current kitchen run  

## Steps to Reproduce
```
vagrant box remove bento/ubuntu-20.04 --all -f
if [ -d ubuntu ]; then
  cd ubuntu
  vagrant destroy -f
  cd ..
fi
rm -fr ubuntu && mkdir ubuntu
cd ubuntu
vagrant init bento/ubuntu-20.04 --box-version 202004.27.0
vagrant up
cd ..
rm -fr test
chef generate cookbook test
cat > update_prune.txt << EOF
    driver:
      box_auto_update: true
      box_auto_prune: true

EOF
sed -i '.bak' '/  - name: ubuntu-20.04/r update_prune.txt' test/kitchen.yml
cd test
kitchen create ubuntu
```

## Expected Result

kitchen create ubuntu should not fail

## Actual Result

<img width="973" alt="Screen Shot 2020-08-19 at 10 46 32 PM" src="https://user-images.githubusercontent.com/7245678/90714676-d620ae00-e26d-11ea-9dbc-33554e18927b.png">

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by tas50** [comment]
Fixed by https://github.com/test-kitchen/kitchen-vagrant/pull/427
