### ISSUE TITLE
Question: option to reload vm

### ISSUE THREAD

**Issue by goatherd** [test-kitchen/kitchen-vagrant#69]
Sometimes it is needed to reload the vm to apply changes made in `driver_config`(memory, cpu, synced folders).

Temporarily `$ (cd .kitchen/.kitchen/kitchen-vagrant/{box_name}/ && vagrant reload)` works.

Is there a way to do this through `kitchen` command?

It not, is this planned to be added in later versions?
Maybe the plugin could reload VM when Vagrantfile was updated on  `kitchen converge`. That would seem the most natural to me.

**Comment by poelzi** [comment]
I have like 10-20 kitchen vm's running, which takes forever to converge from scratch. Suspend would be so awesome to save up some memory, when I don't have to work on a cookbook for a while, but can switch back easily.
